### PR TITLE
Srcape Author name of a book from amazon

### PR DESCRIPTION
**Pull request by rajsagare14**
Amazon Scaper returns the authors name of a given book
new amazon scrapper is updated and modified version of amazon scrapper and it fetches both the book and author name and zips them into a list

### CODE REVIEW

**Comment by rajsagare14** [comment]
accept my request and merge it please

**Review by Ankit3k — APPROVED** [review]
I forgot to accept it yesterday... but u should make it a cross-plaform project so that everyone can run on their system(whether it's a linux os or windows!!!).

**Comment by Ankit3k** [comment]
Improve it and also remove unused comments

**Comment by rajsagare14** [comment]
Done thanks

**Pull request merged**
